#include "OBJExporter.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <cmath>
#include <cstring>

OBJExporter::OBJExporter(const std::string& outputPath) : outputPath_(outputPath) {}

void OBJExporter::exportMesh(const Mesh& mesh) {
    meshes_.push_back(mesh);
}

void OBJExporter::exportMeshes(const std::vector<Mesh>& meshes) {
    for (const auto& mesh : meshes) {
        meshes_.push_back(mesh);
    }
}

void OBJExporter::finalize() {
    std::ofstream out(outputPath_, std::ios::binary);
    if (!out.is_open()) {
        throw std::runtime_error("Failed to open output file: " + outputPath_);
    }
    
    writeHeader();
    for (size_t i = 0; i < meshes_.size(); i++) {
        writeMesh(meshes_[i], static_cast<int>(i));
    }
    
    out.close();
}

void OBJExporter::writeHeader() {
    std::ofstream out(outputPath_, std::ios::binary);
    if (!out.is_open()) {
        throw std::runtime_error("Failed to open output file: " + outputPath_);
    }
    out << "# OBJ file exported from OpenDRIVE" << std::endl;
    out << "# Generated by opendrive-mesh" << std::endl;
}

void OBJExporter::writeMesh(const Mesh& mesh, int index) {
    std::ofstream out(outputPath_, std::ios::app);
    if (!out.is_open()) {
        return;
    }
    
    out << "o " << mesh.name << std::endl;
    
    out << std::fixed << std::setprecision(6);
    for (size_t i = 0; i < mesh.vertices.size(); i++) {
        const auto& v = mesh.vertices[i];
        out << "v " << v.x << " " << v.y << " " << v.z << std::endl;
    }
    
    for (size_t i = 0; i < mesh.vertices.size(); i++) {
        const auto& v = mesh.vertices[i];
        float len = std::sqrt(v.nx * v.nx + v.ny * v.ny + v.nz * v.nz);
        if (len > 1e-6) {
            out << "vn " << v.nx / len << " " << v.ny / len << " " << v.nz / len << std::endl;
        } else {
            out << "vn 0 1 0" << std::endl;
        }
    }
    
    for (size_t i = 0; i < mesh.triangles.size(); i++) {
        const auto& t = mesh.triangles[i];
        uint32_t vi0 = static_cast<uint32_t>(t.i0) + 1;
        uint32_t vi1 = static_cast<uint32_t>(t.i1) + 1;
        uint32_t vi2 = static_cast<uint32_t>(t.i2) + 1;
        uint32_t ni0 = static_cast<uint32_t>(t.i0) + 1;
        uint32_t ni1 = static_cast<uint32_t>(t.i1) + 1;
        uint32_t ni2 = static_cast<uint32_t>(t.i2) + 1;
        out << "f " << vi0 << "n" << ni0 << " " << vi1 << "n" << ni1 << " " << vi2 << "n" << ni2 << std::endl;
    }
}
